//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipsMD5
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShipsMD5()
        {
            this.ShipsMD5Detail = new HashSet<ShipsMD5Detail>();
        }
    
        public int ShipsMD5ID { get; set; }
        public string ShipNumber { get; set; }
        public string ShipName { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string Creator { get; set; }
        public string MD5 { get; set; }
        public Nullable<bool> Closed { get; set; }
        public Nullable<System.DateTime> ClosedTime { get; set; }
        public string ShipNote { get; set; }
        public bool AdvancePayment { get; set; }
        public bool Completed { get; set; }
        public bool FinalPayment { get; set; }
        public bool Invoiced { get; set; }
        public bool Paid { get; set; }
        public bool Shiped { get; set; }
        public bool Actual { get; set; }
        public Nullable<int> ShipID { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<System.DateTime> AdvancePaymentDate { get; set; }
        public Nullable<int> AdvancePaymentUserID { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<int> CompletedUserID { get; set; }
        public Nullable<System.DateTime> FinalPaymentDate { get; set; }
        public Nullable<int> FinalPaymentUserID { get; set; }
        public Nullable<System.DateTime> InvoicedDate { get; set; }
        public Nullable<int> InvoicedUserID { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<int> PaidUserID { get; set; }
        public Nullable<System.DateTime> ShipedDate { get; set; }
        public Nullable<int> ShipedUserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipsMD5Detail> ShipsMD5Detail { get; set; }
    }
}
